# Generated by Django 5.2.6 on 2025-09-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6sid0sX921uwm7eagfetKbEn5vOs0l15qCg&s', max_length=200),
        ),
    ]
