# Generated by Django 5.2.6 on 2025-09-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_items_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_price',
            field=models.IntegerField(db_index=True, max_length=500),
        ),
    ]
