# Generated by Django 5.2.6 on 2025-09-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_items_item_name_alter_items_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6),
        ),
    ]
