# Generated by Django 5.2.6 on 2025-09-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_items_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
