# Generated by Django 5.2.6 on 2025-09-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_items_deleted_at_items_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
